import { useEffect, useState } from 'react';
import { fetchCaseStudy, generateCaseNotes, updateCaseNotes, type CaseNotes } from '../utils/backend';
import { DetailSection } from './ui';

const SECTIONS: { key: keyof Omit<CaseNotes, 'keyTerms' | 'generatedAt' | 'model' | 'edited'>; label: string }[] = [
  { key: 'facts', label: 'Facts' },
  { key: 'issue', label: 'Issue' },
  { key: 'rule', label: 'Rule' },
  { key: 'holding', label: 'Holding' },
  { key: 'reasoning', label: 'Reasoning' },
  { key: 'significance', label: 'Significance' },
];

/**
 * "Study notes" section of the Edit Case drawer: generate IRAC notes with
 * ADVOK AI, review/edit each section, or clear them. Saved independently of
 * the rest of the case form.
 */
export default function CaseNotesEditor({ caseId, onChange }: { caseId: string; onChange?: (hasNotes: boolean) => void }) {
  const [notes, setNotes] = useState<CaseNotes | null>(null);
  const [keyTerms, setKeyTerms] = useState('');
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState<'' | 'generate' | 'save' | 'clear'>('');
  const [error, setError] = useState('');
  const [dirty, setDirty] = useState(false);

  useEffect(() => {
    let alive = true;
    setLoading(true);
    fetchCaseStudy(caseId)
      .then((c) => {
        if (!alive) return;
        setNotes(c.notes ?? null);
        setKeyTerms((c.notes?.keyTerms ?? []).join(', '));
        setDirty(false);
      })
      .catch(() => alive && setError('Could not load notes'))
      .finally(() => alive && setLoading(false));
    return () => {
      alive = false;
    };
  }, [caseId]);

  const generate = async () => {
    if (notes && !window.confirm('Regenerate the notes with ADVOK AI? Your edits will be replaced.')) return;
    setBusy('generate');
    setError('');
    try {
      const n = await generateCaseNotes(caseId);
      setNotes(n);
      setKeyTerms(n.keyTerms.join(', '));
      setDirty(false);
      onChange?.(true);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Generation failed');
    } finally {
      setBusy('');
    }
  };

  const save = async () => {
    if (!notes) return;
    setBusy('save');
    setError('');
    try {
      const n = await updateCaseNotes(caseId, {
        ...notes,
        keyTerms: keyTerms.split(',').map((k) => k.trim()).filter(Boolean),
      });
      setNotes(n);
      setKeyTerms(n?.keyTerms.join(', ') ?? '');
      setDirty(false);
      onChange?.(!!n);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Save failed');
    } finally {
      setBusy('');
    }
  };

  const clear = async () => {
    if (!window.confirm('Remove the study notes for this case? Students will regenerate them on next open.')) return;
    setBusy('clear');
    setError('');
    try {
      await updateCaseNotes(caseId, null);
      setNotes(null);
      setKeyTerms('');
      setDirty(false);
      onChange?.(false);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Clear failed');
    } finally {
      setBusy('');
    }
  };

  const aside = (
    <div className="row" style={{ gap: 8 }}>
      {notes && (
        <button className="btn-pill-grey" onClick={clear} disabled={!!busy}>
          {busy === 'clear' ? 'Clearing…' : 'Clear'}
        </button>
      )}
      <button className="btn-pill-grey" onClick={generate} disabled={!!busy || loading}>
        {busy === 'generate' ? 'Generating…' : notes ? 'Regenerate with ADVOK AI' : 'Generate with ADVOK AI'}
      </button>
    </div>
  );

  return (
    <DetailSection title="Study notes (Generate Case Notes tool)" aside={aside}>
      <div style={{ padding: '8px 0', display: 'grid', gap: 12 }}>
        {loading ? (
          <div className="cell-sub">Loading…</div>
        ) : !notes ? (
          <div className="cell-sub">
            No notes yet. Students get them generated automatically the first time they open "Generate Case
            Notes" for this case; generate here to review them first.
          </div>
        ) : (
          <>
            <div className="cell-sub">
              {notes.edited ? 'Edited by the ADVOK team' : `Generated by ${notes.model}`} ·{' '}
              {new Date(notes.generatedAt).toLocaleString()}
            </div>
            {SECTIONS.map((s) => (
              <div key={s.key}>
                <label className="field-label">{s.label}</label>
                <textarea
                  className="input"
                  style={{ height: s.key === 'issue' || s.key === 'holding' ? 70 : 110, padding: 12, resize: 'vertical', lineHeight: 1.5 }}
                  value={notes[s.key]}
                  onChange={(e) => {
                    setNotes({ ...notes, [s.key]: e.target.value });
                    setDirty(true);
                  }}
                />
              </div>
            ))}
            <div>
              <label className="field-label">Key terms (comma-separated; each links to the Legal Dictionary)</label>
              <input
                className="input"
                value={keyTerms}
                onChange={(e) => {
                  setKeyTerms(e.target.value);
                  setDirty(true);
                }}
              />
            </div>
            <div className="row" style={{ gap: 10, justifyContent: 'flex-end' }}>
              <button className="btn-primary" style={{ height: 40, padding: '0 18px' }} onClick={save} disabled={!dirty || !!busy}>
                {busy === 'save' ? 'Saving…' : 'Save notes'}
              </button>
            </div>
          </>
        )}
        {error && <div className="note-box" style={{ marginBottom: 0 }}>{error}</div>}
      </div>
    </DetailSection>
  );
}
