/**
 * A curated court opinion that law students can read in the app. Picked by an
 * admin from CourtListener search results on the Learning Content page.
 */
export type CaseStudyLevel = 'Beginner' | 'Intermediate' | 'Advanced';

/**
 * IRAC-style study notes for a case, generated by ADVOK AI from the syllabus /
 * opinion text and cached here. The admin can edit or regenerate them.
 */
export interface CaseNotes {
  facts: string;
  issue: string;
  rule: string;
  holding: string;
  reasoning: string;
  significance: string;
  keyTerms: string[];
  generatedAt: string;
  /** Model that produced the notes (or 'admin' after a manual rewrite). */
  model: string;
  /** True once the admin has edited the generated text. */
  edited: boolean;
}

export interface CaseStudyRecord {
  id: string;
  /** CourtListener opinion cluster id (one decision). */
  clusterId: number;
  title: string;
  /** Full court name, e.g. "Supreme Court of the United States". */
  court: string;
  /** CourtListener court id, e.g. "scotus". */
  courtId: string;
  /** YYYY-MM-DD */
  dateFiled: string;
  /** Preferred reporter citation, e.g. "384 U.S. 436". */
  citation: string;
  docketNumber: string;
  judges: string;
  /** Practice-area tag shown on the card (Criminal Defense, Civil Rights…). */
  tag: string;
  level: CaseStudyLevel;
  /** Admin-written (or syllabus-seeded) plain-English summary. */
  summary: string;
  /** "Key legal principle" box; admin-written. */
  principle: string;
  /** Court syllabus from CourtListener, when available. */
  syllabus?: string;
  /** Plain text of the lead opinion, fetched with a CourtListener token. */
  opinionText?: string;
  /** Estimated read time in minutes, from the opinion word count. */
  mins: number;
  /** Only published cases are visible to students. */
  published: boolean;
  /** Lower comes first in the app. */
  sortOrder: number;
  reads: number;
  /** Cached study notes; absent until first generated. */
  notes?: CaseNotes;
  addedAt: string;
  updatedAt: string;
}

export const CASE_STUDY_LEVELS: CaseStudyLevel[] = ['Beginner', 'Intermediate', 'Advanced'];
