// Structured study notes for a curated case, generated by ADVOK AI from the
// case's syllabus / opinion text (CourtListener) and the admin's summary.
// Generated once per case and cached on the record; the admin can edit or
// regenerate them.
import type { CaseNotes, CaseStudyRecord } from '../models';
import { AI_MODEL } from '../config';
import { completeJson, isAiConnected } from './ai.service';

const SYSTEM = `You are a law-school teaching assistant inside the ADVOK app.
Write structured case notes a law student can revise from, in the IRAC style.
Return ONLY a JSON object with exactly these string keys: "facts", "issue", "rule", "holding", "reasoning", "significance", and "keyTerms" (an array of 4 to 8 short legal terms that appear in or matter to the case).
Guidelines:
- facts: 3–5 sentences on what happened and the procedural path to this court.
- issue: the legal question(s) the court had to decide, phrased as question(s).
- rule: the legal rule, test or constitutional principle the court applied.
- holding: how the court answered the issue, including the vote if known.
- reasoning: 3–6 sentences on why the court decided that way, including notable dissent/concurrence in one sentence if any.
- significance: 2–4 sentences on why the case matters today and what later doctrine it shaped.
- Plain text only inside the strings: no Markdown, no bullet characters.
- Use only what the provided text supports; if something is unknown, say "not stated in the provided text" rather than guessing. Never invent citations.`;

const MAX_SYLLABUS = 6_000;
const MAX_OPINION = 14_000;

function clip(text: string | undefined, max: number): string {
  const t = (text ?? '').trim();
  if (t.length <= max) return t;
  return `${t.slice(0, max)}\n[... text truncated ...]`;
}

interface RawNotes {
  facts?: unknown;
  issue?: unknown;
  rule?: unknown;
  holding?: unknown;
  reasoning?: unknown;
  significance?: unknown;
  keyTerms?: unknown;
}

const s = (v: unknown, max = 3000) => (typeof v === 'string' ? v.trim().slice(0, max) : '');

export function hasCaseText(record: CaseStudyRecord): boolean {
  return !!(record.syllabus?.trim() || record.opinionText?.trim() || record.summary?.trim());
}

export async function generateCaseNotes(record: CaseStudyRecord): Promise<CaseNotes> {
  if (!isAiConnected()) throw new Error('ADVOK AI is not connected yet');
  if (!hasCaseText(record)) throw new Error('This case has no text to build notes from yet');

  const user = [
    `Case: ${record.title}`,
    `Court: ${record.court}${record.dateFiled ? ` · Decided ${record.dateFiled}` : ''}`,
    record.citation ? `Citation: ${record.citation}` : '',
    record.docketNumber ? `Docket: ${record.docketNumber}` : '',
    record.judges ? `Judges: ${record.judges}` : '',
    record.summary ? `\nEditor's summary:\n${clip(record.summary, 2000)}` : '',
    record.principle ? `\nKey principle (editor):\n${clip(record.principle, 1000)}` : '',
    record.syllabus ? `\nCourt syllabus:\n${clip(record.syllabus, MAX_SYLLABUS)}` : '',
    record.opinionText ? `\nOpinion text (excerpt):\n${clip(record.opinionText, MAX_OPINION)}` : '',
  ]
    .filter(Boolean)
    .join('\n');

  const raw = await completeJson<RawNotes>(SYSTEM, user, { maxTokens: 1400, temperature: 0.2 });
  const keyTerms = Array.isArray(raw.keyTerms)
    ? raw.keyTerms.map((k) => s(k, 60)).filter(Boolean).slice(0, 8)
    : [];
  const notes: CaseNotes = {
    facts: s(raw.facts),
    issue: s(raw.issue),
    rule: s(raw.rule),
    holding: s(raw.holding),
    reasoning: s(raw.reasoning),
    significance: s(raw.significance),
    keyTerms,
    generatedAt: new Date().toISOString(),
    model: AI_MODEL,
    edited: false,
  };
  if (!notes.facts && !notes.holding && !notes.reasoning) {
    throw new Error('ADVOK AI returned empty notes; try again');
  }
  return notes;
}
