import type { Request, Response } from 'express';
import type { AuthedRequest } from '../middlewares/auth.middleware';
import type { CaseNotes, CaseStudyLevel, CaseStudyRecord, DbShape } from '../models';
import { CASE_STUDY_LEVELS } from '../models/learning.model';
import { generateCaseNotes, hasCaseText } from '../services/case-notes.service';
import { isAiConnected } from '../services/ai.service';
import {
  estimateMinutes,
  fetchOpinionContent,
  hasCourtListenerToken,
  searchOpinions,
} from '../services/courtlistener.service';
import { createId, getDb, saveDb } from '../services/db.service';
import { publishToAll } from '../services/realtime.service';

function studies(db: DbShape): CaseStudyRecord[] {
  db.caseStudies ??= [];
  return db.caseStudies;
}

const str = (v: unknown, max = 2000) => (typeof v === 'string' ? v.trim().slice(0, max) : '');

/** Card shape for lists (no opinion text — that can be hundreds of KB). */
function toCard(c: CaseStudyRecord) {
  return {
    id: c.id,
    clusterId: c.clusterId,
    title: c.title,
    court: c.court,
    courtId: c.courtId,
    dateFiled: c.dateFiled,
    year: c.dateFiled ? c.dateFiled.slice(0, 4) : '',
    citation: c.citation,
    docketNumber: c.docketNumber,
    judges: c.judges,
    tag: c.tag,
    level: c.level,
    summary: c.summary,
    principle: c.principle,
    hasFullText: !!c.opinionText,
    hasSyllabus: !!c.syllabus,
    hasNotes: !!c.notes,
    mins: c.mins,
    published: c.published,
    sortOrder: c.sortOrder,
    reads: c.reads,
    addedAt: c.addedAt,
    updatedAt: c.updatedAt,
  };
}

function defaultPrinciple(tag: string): string {
  return (
    `This case set an important precedent in ${tag || 'US law'}. It is frequently cited in ` +
    'later rulings and remains a cornerstone of legal education in the United States.'
  );
}

// ------------------------------------------------------------- student / app

/** GET /learning/cases — published cases, in admin order. */
export function listPublished(_req: AuthedRequest, res: Response) {
  const list = studies(getDb())
    .filter((c) => c.published)
    .sort((a, b) => a.sortOrder - b.sortOrder || b.addedAt.localeCompare(a.addedAt));
  return res.json({ cases: list.map(toCard) });
}

/** GET /learning/cases/:id — one published case with its full text. Counts a read. */
export function getPublished(req: AuthedRequest, res: Response) {
  const db = getDb();
  const c = studies(db).find((x) => x.id === req.params.id && x.published);
  if (!c) return res.status(404).json({ error: 'Case not found' });
  c.reads += 1;
  saveDb();
  publishToAll('content');
  return res.json({
    case: {
      ...toCard(c),
      syllabus: c.syllabus ?? '',
      opinionText: c.opinionText ?? '',
      notes: c.notes ?? null,
    },
  });
}

/**
 * POST /learning/cases/:id/notes — structured study notes for a published
 * case. Generated by ADVOK AI on first request and cached; later requests
 * return the cached notes instantly.
 */
export async function getOrGenerateNotes(req: AuthedRequest, res: Response) {
  const db = getDb();
  const c = studies(db).find((x) => x.id === req.params.id && x.published);
  if (!c) return res.status(404).json({ error: 'Case not found' });
  if (c.notes) return res.json({ notes: c.notes, cached: true });
  if (!isAiConnected()) {
    return res.status(503).json({ error: 'ADVOK AI is not connected yet' });
  }
  if (!hasCaseText(c)) {
    return res.status(409).json({ error: 'This case has no text to build notes from yet' });
  }
  try {
    c.notes = await generateCaseNotes(c);
    c.updatedAt = new Date().toISOString();
    saveDb();
    return res.json({ notes: c.notes, cached: false });
  } catch (err) {
    return res.status(502).json({ error: err instanceof Error ? err.message : 'Notes failed' });
  }
}

// ------------------------------------------------------------------ admin

/** GET /admin/learning/search?q=&court= — CourtListener opinion search. */
export async function adminSearch(req: Request, res: Response) {
  const q = str(req.query.q, 200);
  const court = str(req.query.court, 40);
  if (!q) return res.status(400).json({ error: 'q is required' });
  try {
    const results = await searchOpinions(q, court);
    const existing = new Set(studies(getDb()).map((c) => c.clusterId));
    return res.json({
      results: results.map((r) => ({ ...r, alreadyAdded: existing.has(r.clusterId) })),
      fullTextAvailable: hasCourtListenerToken(),
    });
  } catch (err) {
    return res
      .status(502)
      .json({ error: err instanceof Error ? err.message : 'CourtListener search failed' });
  }
}

/** GET /admin/learning/cases — every curated case, published or not. */
export function adminList(_req: Request, res: Response) {
  const list = [...studies(getDb())].sort(
    (a, b) => a.sortOrder - b.sortOrder || b.addedAt.localeCompare(a.addedAt),
  );
  return res.json({ cases: list.map(toCard), fullTextAvailable: hasCourtListenerToken() });
}

/** GET /admin/learning/cases/:id — full record including text (for preview). */
export function adminGet(req: Request, res: Response) {
  const c = studies(getDb()).find((x) => x.id === req.params.id);
  if (!c) return res.status(404).json({ error: 'Case not found' });
  return res.json({
    case: {
      ...toCard(c),
      syllabus: c.syllabus ?? '',
      opinionText: c.opinionText ?? '',
      notes: c.notes ?? null,
    },
  });
}

/** POST /admin/learning/cases/:id/notes — (re)generate notes with ADVOK AI. */
export async function adminGenerateNotes(req: Request, res: Response) {
  const db = getDb();
  const c = studies(db).find((x) => x.id === req.params.id);
  if (!c) return res.status(404).json({ error: 'Case not found' });
  if (!isAiConnected()) return res.status(503).json({ error: 'ADVOK AI is not connected yet' });
  try {
    c.notes = await generateCaseNotes(c);
    c.updatedAt = new Date().toISOString();
    saveDb();
    return res.json({ notes: c.notes });
  } catch (err) {
    return res.status(502).json({ error: err instanceof Error ? err.message : 'Notes failed' });
  }
}

/** PUT /admin/learning/cases/:id/notes — admin rewrites any section; null clears the notes. */
export function adminUpdateNotes(req: Request, res: Response) {
  const db = getDb();
  const c = studies(db).find((x) => x.id === req.params.id);
  if (!c) return res.status(404).json({ error: 'Case not found' });
  const b = req.body as { notes?: Partial<CaseNotes> | null } | undefined;
  if (b?.notes === null) {
    delete c.notes;
    c.updatedAt = new Date().toISOString();
    saveDb();
    return res.json({ notes: null });
  }
  const n = b?.notes ?? {};
  const base: CaseNotes = c.notes ?? {
    facts: '', issue: '', rule: '', holding: '', reasoning: '', significance: '',
    keyTerms: [], generatedAt: new Date().toISOString(), model: 'admin', edited: true,
  };
  const text = (v: unknown, prev: string) => (typeof v === 'string' ? str(v, 4000) : prev);
  c.notes = {
    ...base,
    facts: text(n.facts, base.facts),
    issue: text(n.issue, base.issue),
    rule: text(n.rule, base.rule),
    holding: text(n.holding, base.holding),
    reasoning: text(n.reasoning, base.reasoning),
    significance: text(n.significance, base.significance),
    keyTerms: Array.isArray(n.keyTerms)
      ? n.keyTerms.map((k) => str(k, 60)).filter(Boolean).slice(0, 8)
      : base.keyTerms,
    edited: true,
  };
  c.updatedAt = new Date().toISOString();
  saveDb();
  publishToAll('content');
  return res.json({ notes: c.notes });
}

/**
 * POST /admin/learning/cases — adds a case picked from search.
 * Body: search hit fields + tag, level, summary, principle, published.
 * Pulls syllabus + opinion text from CourtListener when a token is set.
 */
export async function adminCreate(req: Request, res: Response) {
  const b = (req.body ?? {}) as Record<string, unknown>;
  // clusterId 0 = added manually (state cases etc. that CourtListener lacks).
  const clusterId = Number(b.clusterId) || 0;
  const title = str(b.title, 300);
  if (!Number.isFinite(clusterId) || clusterId < 0 || !title) {
    return res.status(400).json({ error: 'title is required' });
  }
  const db = getDb();
  if (clusterId > 0 && studies(db).some((c) => c.clusterId === clusterId)) {
    return res.status(409).json({ error: 'This case is already in the list' });
  }
  const level = CASE_STUDY_LEVELS.includes(b.level as CaseStudyLevel)
    ? (b.level as CaseStudyLevel)
    : 'Intermediate';
  const tag = str(b.tag, 60) || 'Constitutional Law';

  let syllabus = str(b.syllabus, 20_000);
  let opinionText = str(b.opinionText, 400_000);
  try {
    const content = clusterId === 0 ? null : await fetchOpinionContent(
      clusterId,
      b.opinionId != null ? Number(b.opinionId) : undefined,
    );
    if (content) {
      syllabus = content.syllabus || syllabus;
      opinionText = content.text;
    }
  } catch (err) {
    console.warn('[learning] opinion fetch failed:', err instanceof Error ? err.message : err);
  }

  const summary = str(b.summary, 5000) || syllabus.slice(0, 1500) || str(b.snippet, 400);
  const now = new Date().toISOString();
  const record: CaseStudyRecord = {
    id: createId(),
    clusterId,
    title,
    court: str(b.court, 200),
    courtId: str(b.courtId, 40),
    dateFiled: str(b.dateFiled, 10),
    citation: str(b.citation, 80),
    docketNumber: str(b.docketNumber, 80),
    judges: str(b.judges, 300),
    tag,
    level,
    summary,
    principle: str(b.principle, 2000) || defaultPrinciple(tag),
    syllabus: syllabus || undefined,
    opinionText: opinionText || undefined,
    mins: estimateMinutes(opinionText || syllabus || summary),
    published: b.published !== false,
    sortOrder: studies(db).length,
    reads: 0,
    addedAt: now,
    updatedAt: now,
  };
  studies(db).push(record);
  saveDb();
  return res.status(201).json({ case: toCard(record) });
}

/** PATCH /admin/learning/cases/:id — edit tag/level/summary/principle/published/order. */
export function adminUpdate(req: Request, res: Response) {
  const db = getDb();
  const c = studies(db).find((x) => x.id === req.params.id);
  if (!c) return res.status(404).json({ error: 'Case not found' });
  const b = (req.body ?? {}) as Record<string, unknown>;
  if (typeof b.title === 'string' && b.title.trim()) c.title = str(b.title, 300);
  if (typeof b.tag === 'string' && b.tag.trim()) c.tag = str(b.tag, 60);
  if (CASE_STUDY_LEVELS.includes(b.level as CaseStudyLevel)) c.level = b.level as CaseStudyLevel;
  if (typeof b.summary === 'string') c.summary = str(b.summary, 5000);
  if (typeof b.principle === 'string') c.principle = str(b.principle, 2000);
  if (typeof b.published === 'boolean') c.published = b.published;
  if (typeof b.sortOrder === 'number' && Number.isFinite(b.sortOrder)) c.sortOrder = b.sortOrder;
  c.updatedAt = new Date().toISOString();
  saveDb();
  publishToAll('content');
  return res.json({ case: toCard(c) });
}

/** POST /admin/learning/cases/:id/refresh-text — re-pull opinion text (needs token). */
export async function adminRefreshText(req: Request, res: Response) {
  if (!hasCourtListenerToken()) {
    return res.status(503).json({ error: 'Set COURTLISTENER_API_TOKEN in backend/.env to fetch opinion text' });
  }
  const db = getDb();
  const c = studies(db).find((x) => x.id === req.params.id);
  if (!c) return res.status(404).json({ error: 'Case not found' });
  try {
    const content = await fetchOpinionContent(c.clusterId);
    if (content) {
      c.syllabus = content.syllabus || c.syllabus;
      c.opinionText = content.text || c.opinionText;
      c.mins = estimateMinutes(c.opinionText || c.syllabus || c.summary);
      c.updatedAt = new Date().toISOString();
      saveDb();
    }
    return res.json({ case: toCard(c) });
  } catch (err) {
    return res
      .status(502)
      .json({ error: err instanceof Error ? err.message : 'CourtListener fetch failed' });
  }
}

/** PUT /admin/learning/cases/order — body: { ids: [...] } sets sortOrder by position. */
export function adminReorder(req: Request, res: Response) {
  const ids = Array.isArray((req.body ?? {}).ids) ? ((req.body as { ids: unknown[] }).ids as string[]) : null;
  if (!ids) return res.status(400).json({ error: 'ids must be an array' });
  const db = getDb();
  const list = studies(db);
  ids.forEach((id, i) => {
    const c = list.find((x) => x.id === id);
    if (c) c.sortOrder = i;
  });
  saveDb();
  publishToAll('content');
  return res.json({ ok: true });
}

/** DELETE /admin/learning/cases/:id */
export function adminDelete(req: Request, res: Response) {
  const db = getDb();
  const list = studies(db);
  const i = list.findIndex((x) => x.id === req.params.id);
  if (i === -1) return res.status(404).json({ error: 'Case not found' });
  list.splice(i, 1);
  saveDb();
  publishToAll('content');
  return res.json({ ok: true });
}
